name: build
on:
  push:
    paths:
      - 'src/*'
  pull_request:
    paths:
      - 'src/*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [16.04, 18.04]
        solver: [CNN, NN]
        include:
          - os: 16.04
            solver: SVM
    container:
      image: ubuntu:${{ matrix.os }}
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt-get update -y
      - run: apt-get install -y libtool-bin libopencv-dev
      - uses: actions/checkout@v2
      - run: (cd src && make SOLVER=${{ matrix.solver }} library all && make SOLVER=${{ matrix.solver }} install)
      - run: ldconfig /usr/local/lib
      - run: /usr/local/bin/kocr
